name: Generate Blog List

on:
  push:
    schedule:
      - cron "0 */1 * * *"

jobs:
  blog:
    runs-on: ubuntu-latest
    name: Fetch and Generate Blog Posts
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Readme Blog Post Action
        uses: ErrorGamer2000/github-readme-blog-post-action@v1
        with:
          feed_urls: "https://vuyisile.com/feed/"
          show_feed_title: false
          show_feed_description: false
          show_read_more: false
          show_last_updated_date: false
          show_feed_data: false

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save Generated Blog Posts
          skip_checkout: true
